--- #YAML:1.0
name:               CPAN-ParseDistribution
version:            1.4
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:      0
    Archive::Zip:      0
    File::Find::Rule:  0
    File::Path:        0
    File::Temp:        0
    YAML:              0.6
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
